apiVersion: "cis.f5.com/v1"
kind: ExternalDNS
metadata:
  name: edns-echo
  namespace: nginx-ingress
  labels:
    f5cr: "true"
spec:
  domainName: echo.example.com
  dnsRecordType: A
  loadBalanceMethod: round-robin
  pools:
  - dnsRecordType: A
    loadBalanceMethod: round-robin
    dataServerName: /Common/bigip1
    monitor:
      type: http
      send: "GET /api HTTP/1.1\r\nHost: echo.example.com\r\n"
      recv: ""
      interval: 10
      timeout: 30
